<?php

/**
 * Implementation of hook_menu
 */
function disableemailchange_menu() {
  $items = array();
  $items['admin/settings/disableemailchange'] = array(
    'title' => 'Disable Email Change Module Settings',
    'type'  => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('disableemailchange_settings_form'),
    'access arguments' => array('access administration pages'),
  );
  return $items;
}

/**
 * Implementation of hook_perm
 */
function disableemailchange_perm() {
  return array('disable changing own email');
}

/**
 * Implementation of hook_form_alter
 */
function disableemailchange_form_alter(&$form, &$form_state, $form_id) {
  if ('user_profile_form' == $form_id) {
    $admin = user_access('administer users');
    global $user;
    if ($admin || ($user->uid && !user_access('disable changing own email'))) {
      // leave default forms to itself
    } else {
      $form['account']['display_email'] = array(
        '#type'     => 'item',
        '#title'    => 'Email',
        '#value'    => $user->mail,
        '#weight'   => -1,
      );
      // we still need to return the value for validation
      $form['account']['mail'] = array(
        '#type'     => 'value',
        '#title'    => 'Email',
        '#value'    => $user->mail,
      );
    }
    return;
  }

  if ('user_register' == $form_id) {
    if (variable_get('disableemailchange_show_user_registration', false)) {
      $form['account']['mail']['#description'] .= '<br/><b>' . t('Note: You cannot change email after registration.') .
        '</br>';
    }
    return;
  }
}

function disableemailchange_settings_form() {
  $form = array();
  $form['disableemailchange_show_user_registration'] = array(
    '#type'           => 'checkbox',
    '#default_value'  => variable_get('disableemailchange_show_user_registration', false),
    '#title'          => t('Show email cannot change information on user registration'),
    '#description'    => t('If checked, users will see a warning that mentions that they cannot change their email
      address after registration.'),
  );

  return system_settings_form($form);
}
